name: werewolf_client
description: Game were wolf online with flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Notification
  flutter_local_notifications: ^4.0.1+2
  firebase_messaging: ^8.0.0-dev.14

  connectivity: ^2.0.2
  rxdart: ^0.25.0
  cupertino_icons: ^1.0.0
  flutter_easyloading: ^2.2.2
  safe_config: ^2.0.2
  get: ^3.26.0
  dio: ^3.0.10
  socket_io_client: ^0.9.12
  get_storage: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Fira
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-Black.ttf
          weight: 900
        - asset: assets/fonts/FiraSans-Medium.ttf
          weight: 800
        - asset: assets/fonts/FiraSans-Medium.ttf
          weight: 700
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/FiraSans-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraSans-Light.ttf
          weight: 200
        - asset: assets/fonts/FiraSans-Light.ttf
          weight: 100